import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BelowHeader } from "./components/belowHeader";
import MainHeader from "./components/mainHeader";
import Navbar from "./components/navbar";
import SelectedNavigation from "./components/selectedNavigation";
import BeforeFooter from "./components/beforeFooter";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainHeader />
        <BelowHeader />
        <Navbar />
        <SelectedNavigation />
        {children}
        <BeforeFooter />
        <Footer />
      </body>
    </html>
  );
}
